function requireAdmin(req, res, next) {
  const token = req.headers['x-admin-token'] || req.query.token;
  const adminPassword = process.env.ADMIN_PASSWORD || 'kw@admin2024';
  
  // Allow if token matches password (direct) 
  // OR if it starts with 'kw:' (indicating it was generated by our login route)
  if (token === adminPassword) return next();
  
  if (token) {
    try {
      const decoded = Buffer.from(token, 'base64').toString();
      if (decoded.startsWith('kw:')) return next();
    } catch(e) {}
  }

  res.status(401).json({ error: 'Unauthorized' });
}

module.exports = { requireAdmin };
